/**
 * .what = the "generated — do not edit" banner prepended to every emitted file
 * .why = readers should re-run the codegen, not hand-edit the output (uc.1); the
 *        robot-arm 🦾 signals at a glance that a machine wrote this file
 * .note = the glyph must survive the biome/stdin format pass — not every emoji does, so 🦾 is
 *         asserted to round-trip cleanly in formatTypescript.integration.test.ts
 */
export const banner = `/**
 * 🦾 generated by \`sdk-aws-lambda gen\` — do not edit.
 * re-run the codegen to update.
 */`;
